AY2324S1-CS2103T-T17-3/tp

- docs/team/dishenggg.md
> Create PPP skeleton for Di Sheng

- docs/_config.yml
- docs/_sass/minima/_base.scss
Change AB-3 to Tutor Connect
Update repo link
closes #19
> Update site-wide settings for Jekyll

- docs/DeveloperGuide.md
Target user profile, value proposition, and user stories:
Use cases:
Non-functional requirements (NFRs):
Glossary:
> Update Developer Guide for v1.1

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
Update occurrences of persons in `find` commands to `tutors`.
> Update find command to display as tutors

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/schedule/Schedule.java
- src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
- src/test/java/seedu/address/model/schedule/ScheduleTest.java
- src/test/java/seedu/address/testutil/ScheduleUtil.java
Add implementation for `add-s`.
> Add schedule command

- src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
- src/test/java/seedu/address/testutil/TypicalSchedules.java
Fixes bug #110 where formatter was being saved in schedules for the json save file.
> Update formatter to be static in JsonAdaptedSchedule

- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
> Remove Address from PersonCard UI

- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
- src/test/java/seedu/address/logic/commands/AddTutorCommandTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
Fix the issue of deleting tutor not deleting associated schedules.
> Delete tutor schedules

- docs/UserGuide.md
* Add Glossary (definitions, parameter information, parameter format)
* Add edit-s in summary
* Add headers for future sections
> Add headers, edit-s summary, and glossary

- src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
- src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
- src/test/java/seedu/address/logic/commands/EditScheduleDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/testutil/EditScheduleDescriptorBuilder.java
- src/test/java/seedu/address/testutil/ScheduleUtil.java
- src/test/java/seedu/address/testutil/TypicalSchedules.java
Add EditScheduleCommand in AddressBookParserTest
> Update AddressBookParser test

- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Adds test for unmark in AddressBookParserTest.
> Add parser unmark command test

- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/test/java/seedu/address/model/util/SampleDataUtilTest.java
SampleDataUtil now creates sample schedules for every sample person created.
> Update SampleDataUtil to include schedules

- src/test/java/seedu/address/model/schedule/UniqueScheduleListTest.java
Add tests for 
- equals
- iterator
- hashcode
> Add more tests for UniqueScheduleList

- src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
- src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
- src/main/java/seedu/address/model/schedule/Time.java
- src/test/data/JsonSerializableAddressBookTest/clashingScheduleAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidScheduleAddressBook.json
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/schedule/EndTimeTest.java
- src/test/java/seedu/address/model/schedule/StartTimeTest.java
- src/test/java/seedu/address/model/schedule/TimeTest.java
UG will be updated in another PR into update-ug-for-v1.3 branch to reduce conflicts
> Remove seconds from time related commands

- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Adds test for mark in AddressBookParserTest.
> Add parser mark command test

- src/main/java/seedu/address/logic/commands/EditTutorCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
- src/test/java/seedu/address/logic/commands/AddTutorCommandTest.java
- src/test/java/seedu/address/logic/commands/EditTutorCommandTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
Editing tutor now updates the tutor reference in each associated schedule with the new tutor object.
> Update associated schedule's tutors when tutor is edited

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/ShowCalendarCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/schedule/ScheduleIsOnDatePredicate.java
- src/main/java/seedu/address/ui/CalendarPanel.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/BlueTheme.css
- src/main/resources/view/CalendarPanel.fxml
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/LightTheme.css
- src/main/resources/view/ListsPanel.fxml
- src/main/resources/view/MainWindow.fxml
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
- src/test/java/seedu/address/logic/commands/AddTutorCommandTest.java
- src/test/java/seedu/address/logic/commands/ShowCalendarCommandTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/schedule/ScheduleIsOnDatePredicateTest.java
Separates the list used for schedule list and calendar view, removing coupling between the two.
> Add list for calendar view into ModelManager

- src/main/resources/view/MainWindow.fxml
> Update main window title to TutorConnect

- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/main/resources/view/StatusBarFooter.fxml
> Add current datetime to status bar

- src/main/java/seedu/address/ui/CalendarRow.java
Fixes [misalignment](https://github.com/AY2324S1-CS2103T-T17-3/tp/issues/219) in consecutive schedules.
> Fix schedules position in calendar view

- src/main/java/seedu/address/MainApp.java
> Add JAR release for v1.3

- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/model/ModelManagerTest.java
Fixes status being set to pending when the assigned tutor is edited.
> Fix status lost on tutor edit

- src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
- Typing `list-s` after passing 12am today will update schedules today to past schedules.
> Fixed list-s to update schedules before today after the day has passed

- docs/DeveloperGuide.md
Adds description and proposed implementation for the following planned enhancements:
- Allow partial name search for find command
> Update planned enhancements in DG

- docs/DeveloperGuide.md
Replaces `UI for calendar to use colours to reflect status of schedules` planned enhancement with `Help window flickering when displayed`.
> Add planned enhancement for help window flickering

- src/main/java/seedu/address/logic/parser/ThemeCommandParser.java
- src/test/java/seedu/address/logic/parser/ThemeCommandParserTest.java
Reverts AY2324S1-CS2103T-T17-3/tp#295
> Revert "Fix ThemeCommandParser to only accept 1 parameter"

- src/main/resources/view/CalendarRow.fxml
- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/ScheduleListCard.fxml
Reverts AY2324S1-CS2103T-T17-3/tp#305
> Revert "Prevent long fields from being truncated"

- src/test/java/seedu/address/logic/parser/MarkScheduleCommandParserTest.java
Reverts AY2324S1-CS2103T-T17-3/tp#296
> Revert "Add test for bug fix of multiple prefixes for mark command"

- src/main/java/seedu/address/ui/CalendarCard.java
> Revert "Truncate calendar view when schedules are short"

- src/main/java/seedu/address/logic/parser/MarkScheduleCommandParser.java
Reverts AY2324S1-CS2103T-T17-3/tp#293
> Revert "Fix bug for multiple prefixes in mark command"

- src/main/java/seedu/address/MainApp.java
> Add JAR release for v1.4
